Algoritmo "Contador1a10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/07/2023
Var
// Seção de Declarações das variáveis 
    C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    para C <- 1 ate 10 faca
         escreval(C)
    fimpara

Fimalgoritmo